import { expect, test } from '@playwright/test'

test('task markers stay atomic for Home, arrow navigation, Backspace, and Delete', async ({ page }) => {
  await page.goto('/?fixture=task-list-keyboard')
  const editor = page.locator('.cm-content')
  const markdown = page.getByTestId('markdown-output')
  const offset = page.getByTestId('selection-offset')
  await editor.press('End')
  await editor.press('Home')
  await expect(offset).toHaveText('6')
  await editor.press('ArrowLeft')
  await expect(offset).toHaveText('0')
  await editor.press('ArrowRight')
  await expect(offset).toHaveText('6')
  await editor.press('Backspace')
  await expect(markdown).toHaveText('one')
  await expect(offset).toHaveText('0')
  await editor.press('ControlOrMeta+z')
  await expect(markdown).toHaveText('- [ ] one')
  await editor.press('ControlOrMeta+Shift+z')
  await expect(markdown).toHaveText('one')
  await editor.type('N')
  await expect(markdown).toHaveText('None')

  await page.getByRole('button', { name: 'Reset task' }).click()
  await editor.press('End')
  await editor.press('Home')
  await editor.press('ArrowLeft')
  await editor.press('Delete')
  await expect(markdown).toHaveText('one')
  await expect(offset).toHaveText('0')
})

test('Delete at the start of an indented task keeps its indentation', async ({ page }) => {
  await page.goto('/?fixture=task-list-keyboard')
  const editor = page.locator('.cm-content')
  const markdown = page.getByTestId('markdown-output')
  const offset = page.getByTestId('selection-offset')
  await page.getByRole('button', { name: 'Reset nested task' }).click()
  await page.getByRole('button', { name: 'Focus task end' }).click()
  await editor.press('Tab')
  await expect(markdown).toHaveText('- parent\n    - [ ] one')
  await editor.press('Home')
  await editor.press('ArrowLeft')
  await expect(offset).toHaveText('9')
  await editor.press('Delete')
  await expect(markdown).toHaveText('- parent\n    one')
  await expect(offset).toHaveText('13')
})

test('selection and word deletion cannot expose part of a live task checkbox', async ({ page }) => {
  await page.goto('/?fixture=task-list-keyboard')
  const editor = page.locator('.cm-content')
  const markdown = page.getByTestId('markdown-output')
  const offset = page.getByTestId('selection-offset')

  for (const keys of [
    ['Shift+ArrowLeft', 'Backspace'],
    ['Shift+ArrowLeft', 'Shift+ArrowLeft', 'Backspace'],
    ['ArrowLeft', 'Shift+ArrowRight', 'Delete'],
    ['Shift+Home', 'Backspace'],
    ['Alt+Backspace'],
    ['ControlOrMeta+Backspace'],
  ]) {
    await page.getByRole('button', { name: 'Reset task', exact: true }).click()
    await page.getByRole('button', { name: 'Focus task end' }).click()
    await editor.press('Home')
    await expect(offset).toHaveText('6')
    for (const key of keys) await editor.press(key)
    await expect(markdown).toHaveText('one')
    await expect(page.locator('.me-checkbox')).toHaveCount(0)
  }
})

test('entering live mode moves a source caret out of hidden checkbox syntax', async ({ page }) => {
  await page.goto('/?fixture=task-list-keyboard')
  const editor = page.locator('.cm-content')
  const markdown = page.getByTestId('markdown-output')
  const offset = page.getByTestId('selection-offset')
  await page.getByRole('button', { name: 'Mode: live' }).click()
  await page.getByRole('button', { name: 'Focus task end' }).click()
  await editor.press('Home')
  for (let i = 0; i < 3; i++) await editor.press('ArrowRight')
  await expect(offset).toHaveText('3')
  await page.getByRole('button', { name: 'Mode: source' }).click()
  await expect(page.locator('.me-checkbox')).toHaveCount(1)
  await expect(offset).toHaveText('6')
  await page.getByRole('button', { name: 'Restore editor focus' }).click()
  await editor.press('Z')
  await expect(markdown).toHaveText('- [ ] Zone')
})

test('only valid task items receive a live checkbox', async ({ page }) => {
  await page.goto('/?fixture=task-list-keyboard')
  await page.getByRole('button', { name: 'Reset malformed task' }).click()
  await expect(page.getByTestId('markdown-output')).toHaveText('- [ ]one')
  await expect(page.locator('.me-checkbox')).toHaveCount(0)
  await page.getByRole('button', { name: 'Reset code-like task' }).click()
  await expect(page.getByTestId('markdown-output')).toHaveText('    - [ ] code')
  await expect(page.locator('.me-checkbox')).toHaveCount(0)
  await page.getByRole('button', { name: 'Reset list code task' }).click()
  await expect(page.getByTestId('markdown-output')).toHaveText('- parent\n\n        - [ ] code')
  await expect(page.locator('.me-checkbox')).toHaveCount(0)
})

test('live Tab keeps a lone top-level item a list while source Tab edits raw Markdown', async ({ page }) => {
  await page.goto('/?fixture=task-list-keyboard')
  const editor = page.locator('.cm-content')
  const markdown = page.getByTestId('markdown-output')
  for (const [button, value] of [['Reset task', '- [ ] one'], ['Reset bullet', '- one']]) {
    await page.getByRole('button', { name: button, exact: true }).click()
    await page.getByRole('button', { name: 'Focus task end' }).click()
    await editor.press('Tab')
    await expect(markdown).toHaveText(value)
    await expect(editor).toBeFocused()
    await editor.press('Shift+Tab')
    await expect(markdown).toHaveText(value)
    await expect(editor).toBeFocused()
  }

  await page.getByRole('button', { name: 'Reset task', exact: true }).click()
  await page.getByRole('button', { name: 'Mode: live' }).click()
  await page.getByRole('button', { name: 'Focus task end' }).click()
  await editor.press('Tab')
  await expect(markdown).toHaveText('    - [ ] one')
})

test('Tab uses enough indentation beneath a wide ordered marker and Shift-Tab reverses it', async ({ page }) => {
  await page.goto('/?fixture=task-list-keyboard')
  const editor = page.locator('.cm-content')
  const markdown = page.getByTestId('markdown-output')
  await page.getByRole('button', { name: 'Reset wide ordered task' }).click()
  await page.getByRole('button', { name: 'Focus task end' }).click()
  await editor.press('Tab')
  await expect(markdown).toHaveText('123. parent\n     - [ ] child')
  await expect(page.locator('.me-checkbox')).toHaveCount(1)
  await editor.press('Shift+Tab')
  await expect(markdown).toHaveText('123. parent\n- [ ] child')
  await expect(page.locator('.me-checkbox')).toHaveCount(1)
})

test('task items continue, exit, indent, and expose raw syntax in source mode', async ({ page }) => {
  await page.goto('/?fixture=task-list-keyboard')
  const editor = page.locator('.cm-content')
  const markdown = page.getByTestId('markdown-output')
  await editor.press('End')
  await editor.press('Enter')
  await expect(markdown).toHaveText('- [ ] one\n- [ ] ')
  await editor.press('Enter')
  await expect(markdown).toHaveText('- [ ] one\n')

  await page.getByRole('button', { name: 'Reset nested task' }).click()
  await expect(markdown).toHaveText('- parent\n- [ ] one')
  await page.getByRole('button', { name: 'Focus task end' }).click()
  await expect(page.getByTestId('selection-offset')).toHaveText('18')
  await editor.press('Tab')
  await expect(markdown).toHaveText('- parent\n    - [ ] one')
  await expect(page.getByTestId('selection-offset')).toHaveText('22')
  await editor.press('Shift+Tab')
  await expect(markdown).toHaveText('- parent\n- [ ] one')
  await expect(page.getByTestId('selection-offset')).toHaveText('18')

  await page.getByRole('button', { name: 'Reset task' }).click()
  await page.getByRole('button', { name: 'Mode: live' }).click()
  await expect(page.locator('.me-checkbox')).toHaveCount(0)
  await editor.click()
  await editor.press('Home')
  await editor.press('ArrowRight')
  await editor.press('ArrowRight')
  await editor.press('Delete')
  await expect(markdown).toHaveText('-  ] one')

  await page.getByRole('button', { name: 'Reset task' }).click()
  await expect(markdown).toHaveText('- [ ] one')
  await page.getByRole('button', { name: 'Focus task end' }).click()
  await editor.press('Home')
  for (let i = 0; i < 6; i++) await editor.press('ArrowRight')
  await expect(page.getByTestId('selection-offset')).toHaveText('6')
  await editor.press('Backspace')
  await expect(markdown).toHaveText('- [ ]one')
})
